name: water_bottle_example
description: A beautiful bottle for your project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0

environment:
  sdk: ">=3.0.0 <=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  path_parsing: ^1.0.0
  water_bottle: 
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
